### ISSUE TITLE
SphereTess and other GL3+ examples not working on P3.0b5 + OSX 10.10.4

### ISSUE THREAD

**Issue by stmaccarelli** [codeanticode/pshader-experiments#1]
Hello, when trying to run your pshader experiments on my MacBook Pro Early 2011 (AMD Radeon HD 6750M 1024 MB), except for the BlueMarble (that uses GLSL 2 I guess), I get the following error;

<code>
java.lang.RuntimeException: com.jogamp.opengl.GLException: Caught RuntimeException: Cannot compile fragment shader:
ERROR: 0:5: Regular non-array variable 'fragColor' may not be redeclared
 on thread main-Display-.macosx_nil-1-EDT-1
    at jogamp.newt.DefaultEDTUtil.invokeImpl(DefaultEDTUtil.java:249)
    at jogamp.newt.DefaultEDTUtil.invoke(DefaultEDTUtil.java:163)
    at jogamp.newt.DisplayImpl.runOnEDTIfAvail(DisplayImpl.java:427)
    at jogamp.newt.WindowImpl.runOnEDTIfAvail(WindowImpl.java:2133)
    at jogamp.newt.WindowImpl.setVisible(WindowImpl.java:1024)
    at jogamp.newt.WindowImpl.setVisible(WindowImpl.java:1029)
    at com.jogamp.newt.opengl.GLWindow.setVisible(GLWindow.java:499)
    at processing.opengl.PSurfaceJOGL.setVisible(PSurfaceJOGL.java:387)
    at processing.core.PApplet.showSurface(PApplet.java:10256)
    at processing.core.PApplet.runSketch(PApplet.java:10240)
    at processing.core.PApplet.main(PApplet.java:9969)
Caused by: com.jogamp.opengl.GLException: Caught RuntimeException: Cannot compile fragment shader:
ERROR: 0:5: Regular non-array variable 'fragColor' may not be redeclared
 on thread main-Display-.macosx_nil-1-EDT-1
    at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1311)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1131)
    at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:680)
    at jogamp.opengl.GLAutoDrawableBase.defaultWindowResizedOp(GLAutoDrawableBase.java:259)
    at com.jogamp.newt.opengl.GLWindow.access$200(GLWindow.java:119)
    at com.jogamp.newt.opengl.GLWindow$2.windowResized(GLWindow.java:141)
    at jogamp.newt.WindowImpl.consumeWindowEvent(WindowImpl.java:3682)
    at jogamp.newt.WindowImpl.sendWindowEvent(WindowImpl.java:3616)
    at jogamp.newt.WindowImpl.setVisibleActionImpl(WindowImpl.java:1003)
    at jogamp.newt.WindowImpl$VisibleAction.run(WindowImpl.java:1015)
    at com.jogamp.common.util.RunnableTask.run(RunnableTask.java:150)
    at jogamp.newt.DefaultEDTUtil$NEDT.run(DefaultEDTUtil.java:372)
Caused by: java.lang.RuntimeException: Cannot compile fragment shader:
ERROR: 0:5: Regular non-array variable 'fragColor' may not be redeclared

    at processing.core.PGraphics.showException(PGraphics.java:8078)
    at processing.opengl.PShader.compileFragmentShader(PShader.java:1023)
    at processing.opengl.PShader.compile(PShader.java:940)
    at processing.opengl.PShader.init(PShader.java:906)
    at processing.opengl.PShader.getUniformLoc(PShader.java:619)
    at processing.opengl.PShader.setUniformImpl(PShader.java:750)
    at processing.opengl.PShader.set(PShader.java:429)
    at SphereTess.setup(SphereTess.java:55)
    at processing.core.PApplet.handleDraw(PApplet.java:2376)
    at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:654)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:691)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:673)
    at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:442)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1277)
    ... 11 more
</code>

**Comment by stmaccarelli** [comment]
if I comment this line
//out vec4 fragColor;
 in the fragment shader, that example run.

But wel, for me every example has some errors. Are they tested on Processing 3.0b5 ?

**Comment by codeanticode** [comment]
I updated them to work on 3.0 final.
